import { Route } from "expo-router";
import { useGlobalContext } from "@/context/GlobalProvider";
import { Platform } from "react-native";

const driverHomeBoxes = [
  {
    id: 1,
    source: require("@/assets/images/find-cargo-by-location-icon.png"),
    text: "باریابی",
    route: "/find-cargo-by-location"
  },
  {
    id: 2,
    source: require("@/assets/images/favicon.png"), // New icon for announcement cargo
    text: "اعلام بار",
    route: "/announcement-cargos" // New route for announcement cargo location
  },
  {
    id: 3,
    source: require("@/assets/images/account-icon.png"),
    text: "حساب کاربری",
    route: "/driver-account"
  },
  {
    id: 4,
    source: require("@/assets/images/tools-icon.png"),
    text: "ابزار",
    route: "/driver-tools"
  }
];

const cargoOwnerHomeBoxes = [
  {
    id: 1,
    source: require("@/assets/images/add-cargo-icon.png"),
    text: "ایجاد بار جدید",
    route: "/create-cargo"
  },
  {
    id: 2,
    source: require("@/assets/images/add-cargo-icon.png"),
    text: "تاریخچه بارها",
    route: "/cargo-history"
  },
  {
    id: 3,
    source: require("@/assets/images/account-icon.png"),
    text: "حساب کاربری",
    route: "/cargo-owner-account"
  },
  {
    id: 4,
    source: require("@/assets/images/tools-icon.png"),
    text: "ابزار",
    route: "/cargo-owner-tools"
  }
];

const tabBoxes = (role: string) => {
  const role1Tabs = [
    {
      name: "driver-tools",
      title: "ابزار",
      iconName: "wrench.fill"
    },
    {
      name: "driver-account",
      title: "کاربر",
      iconName: "person.crop.circle"
    },

    {
      name: "driver-home",
      title: "خانه",
      iconName: "house.fill"
    }
  ];
  const role2Tabs = [
    {
      name: "cargo-owner-tools",
      title: "ابزار",
      iconName: "wrench.fill"
    },
    {
      name: "cargo-owner-account",
      title: "کاربر",
      iconName: "person.crop.circle"
    },
    {
      name: "cargo-owner-home",
      title: "خانه",
      iconName: "house.fill"
    }
  ];
  if (role === "1") {
    return role1Tabs;
  } else {
    return role2Tabs;
  }
};

const truckTypes = [
  { label: "تریلی کفی", value: "1" },
  { label: "تریلی کفی ۱۳.۶۰", value: "2" },
  { label: "تریلی بغلدار", value: "3" },
  { label: "تریلی نیم لبه", value: "4" },
  { label: "تریلی چادری", value: "5" },
  { label: "تریلی کمپرسی", value: "6" },
  { label: "تریلی یخچالی", value: "7" },
  { label: "تریلی تانکر", value: "8" },
  { label: "جفت معمولی", value: "9" },
  { label: "جفت چادری", value: "10" },
  { label: "جفت کمپرسی", value: "11" },
  { label: "جفت یخچالی", value: "12" },
  { label: "تک معمولی", value: "13" },
  { label: "تک کمپرسی", value: "14" },
  { label: "تک چادری", value: "15" },
  { label: "تک یخچالی", value: "16" },
  { label: "خاور اطاقدار", value: "17" },
  { label: "خاور مسقف", value: "18" },
  { label: "خاور کمپرسی", value: "19" },
  { label: "خاور یخچالی", value: "20" },
  { label: "وانت نیسان", value: "21" },
  { label: "کامیون خودروبر", value: "22" }
];

const cargoTypes = [
  { value: "101", label: "کنسانتره سنگ آهن" },
  { value: "102", label: "گندله سنگ آهن" },
  { value: "103", label: "سنگ آهن هماتیت" },
  { value: "104", label: "سنگ آهن مگنتیت" },
  { value: "105", label: "سنگ مس" },
  { value: "106", label: "سنگ سرب" },
  { value: "107", label: "سنگ روی" },
  { value: "108", label: "سنگ گچ" },
  { value: "109", label: "سنگ مرمر" },
  { value: "110", label: "سنگ گرانیت" },
  { value: "111", label: "سنگ آهک" },
  { value: "112", label: "سنگ نمک" },
  { value: "113", label: "زغال سنگ حرارتی" },
  { value: "114", label: "زغال سنگ کک‌شو" },
  { value: "115", label: "سنگ پومیس" },
  { value: "201", label: "پلیاتیلن سبک (LDPE)" },
  { value: "202", label: "پلیاتیلن سنگین (HDPE)" },
  { value: "203", label: "پلیپروپیلن (PP)" },
  { value: "204", label: "پلیوینیل کلراید (PVC)" },
  { value: "205", label: "پلیاستایرن (PS)" },
  { value: "206", label: "اتیلن گلایکول" },
  { value: "207", label: "متانول صنعتی" },
  { value: "208", label: "اوره گرانوله" },
  { value: "209", label: "آمونیاک مایع" },
  { value: "210", label: "بنزن" },
  { value: "211", label: "تولوئن" },
  { value: "212", label: "زایلن" },
  { value: "213", label: "استایرن مونومر" },
  { value: "214", label: "اتیلن اکساید" },
  { value: "215", label: "پارازایلن" },
  { value: "216", label: "پلی‌اتیلن سبک خطی (LLDPE)" },
  { value: "217", label: "پلی‌بوتیلن ترفتالات (PBT)" },
  { value: "218", label: "پلی‌اتیلن ترفتالات (PET)" },
  { value: "219", label: "اکریلونیتریل بوتادین استایرن (ABS)" },
  { value: "220", label: "پلی‌کربنات (PC)" },
  { value: "221", label: "مونو اتیلن گلایکول (MEG)" },
  { value: "222", label: "دی اتیلن گلایکول (DEG)" },
  { value: "223", label: "تری اتیلن گلایکول (TEG)" },
  { value: "224", label: "اسید استیک" },
  { value: "225", label: "وینیل استات مونومر (VAM)" },
  { value: "226", label: "پلی‌متیل متاکریلات (PMMA)" },
  { value: "227", label: "بوتادین" },
  { value: "228", label: "کربن بلک" },
  { value: "229", label: "دی متیل ترفتالات (DMT)" },
  { value: "230", label: "دی اکتیل فتالات (DOP)" },
  { value: "231", label: "اتیل بنزن" },
  { value: "232", label: "ایزوسیانات‌ها" },
  { value: "233", label: "پروپیلن اکساید" },
  { value: "234", label: "استونیتریل" },
  { value: "235", label: "اپوکسی رزین" },
  { value: "301", label: "گندم" },
  { value: "302", label: "برنج" },
  { value: "303", label: "ذرت" },
  { value: "304", label: "جو" },
  { value: "305", label: "شکر سفید" },
  { value: "306", label: "شکر قهوه‌ای" },
  { value: "307", label: "روغن آفتابگردان" },
  { value: "308", label: "روغن زیتون" },
  { value: "309", label: "پسته خام" },
  { value: "310", label: "بادام درختی" },
  { value: "311", label: "خرما" },
  { value: "312", label: "کشمش" },
  { value: "313", label: "زعفران" },
  { value: "314", label: "چای سیاه" },
  { value: "315", label: "قهوه سبز" },
  { value: "316", label: "روغن سویا" },
  { value: "317", label: "روغن پالم" },
  { value: "318", label: "روغن کلزا" },
  { value: "319", label: "گوشت گاو منجمد" },
  { value: "320", label: "گوشت مرغ منجمد" },
  { value: "321", label: "ماهی تن منجمد" },
  { value: "322", label: "میگو منجمد" },
  { value: "323", label: "شیر خشک صنعتی" },
  { value: "324", label: "پودر آب پنیر" },
  { value: "325", label: "کره بسته‌بندی" },
  { value: "326", label: "پنیر فراوری شده" },
  { value: "327", label: "کنسانتره آب میوه" },
  { value: "328", label: "پوره میوه صنعتی" },
  { value: "329", label: "نشاسته ذرت" },
  { value: "330", label: "گلوتن گندم" },
  { value: "331", label: "سویا" },
  { value: "332", label: "کنجاله سویا" },
  { value: "333", label: "کنجد" },
  { value: "334", label: "عدس" },
  { value: "335", label: "لوبیا" },
  { value: "336", label: "نخود" },
  { value: "337", label: "آرد گندم" },
  { value: "338", label: "نمک تصفیه شده" },
  { value: "339", label: "فلفل سیاه" },
  { value: "340", label: "ادویه کاری" },
  { value: "341", label: "گردو" },
  { value: "342", label: "فندق" },
  { value: "343", label: "عسل طبیعی" },
  { value: "344", label: "آبمیوه کنسانتره" },
  { value: "345", label: "رب گوجه فرنگی" },
  { value: "346", label: "سس مایونز صنعتی" },
  { value: "347", label: "پودر کاکائو" },
  { value: "348", label: "شکلات صنعتی" },
  { value: "349", label: "مالت جو" },
  { value: "350", label: "نشاسته سیب زمینی" },
  { value: "401", label: "مواد منفجره کلاس ۱.۱" },
  { value: "402", label: "گازهای سمی کلاس ۲.۳" },
  { value: "403", label: "مایعات اشتعال‌پذیر کلاس ۳" },
  { value: "404", label: "مواد جامد اشتعال‌پذیر کلاس ۴.۱" },
  { value: "405", label: "مواد اکسیدکننده کلاس ۵.۱" },
  { value: "406", label: "مواد سمی کلاس ۶.۱" },
  { value: "407", label: "مواد رادیواکتیو کلاس ۷" },
  { value: "408", label: "مواد خورنده کلاس ۸" },
  { value: "409", label: "مواد خطرناک متفرقه کلاس ۹" },
  { value: "410", label: "مواد منفجره کلاس ۱.۲" },
  { value: "411", label: "مواد منفجره کلاس ۱.۳" },
  { value: "412", label: "مواد منفجره کلاس ۱.۴" },
  { value: "413", label: "مواد منفجره کلاس ۱.۵" },
  { value: "414", label: "مواد منفجره کلاس ۱.۶" },
  { value: "415", label: "گازهای قابل اشتعال کلاس ۲.۱" },
  { value: "416", label: "گازهای غیرقابل اشتعال کلاس ۲.۲" },
  { value: "417", label: "مایعات اشتعال‌پذیر گروه I" },
  { value: "418", label: "مایعات اشتعال‌پذیر گروه II" },
  { value: "419", label: "مایعات اشتعال‌پذیر گروه III" },
  { value: "420", label: "مواد جامد قابل اشتعال خودبخود کلاس ۴.۲" },
  { value: "421", label: "مواد جامد واکنش‌پذیر با آب کلاس ۴.۳" },
  { value: "422", label: "پراکسیدهای آلی کلاس ۵.۲" },
  { value: "423", label: "مواد عفونی کلاس ۶.۲" },
  { value: "424", label: "مواد رادیواکتیو فرم خاص" },
  { value: "425", label: "مواد رادیواکتیو با اکتیویته کم" },
  { value: "426", label: "هگزافلوراید اورانیوم" },
  { value: "427", label: "مواد خورنده اسیدی" },
  { value: "428", label: "مواد خورنده بازی" },
  { value: "429", label: "سیانیدها" },
  { value: "430", label: "آفت‌کش‌ها" },
  { value: "431", label: "آرسنیک و ترکیبات آن" },
  { value: "432", label: "جیوه و ترکیبات آن" },
  { value: "433", label: "سرب و ترکیبات آن" },
  { value: "434", label: "کادمیوم و ترکیبات آن" },
  { value: "435", label: "آزبست" },
  { value: "436", label: "پلی‌کلرینیتد بی‌فنیل‌ها (PCB)" },
  { value: "437", label: "دی‌اکسین‌ها" },
  { value: "438", label: "فوران‌ها" },
  { value: "439", label: "نیتروگلیسیرین" },
  { value: "440", label: "تری‌نیتروتولوئن (TNT)" },
  { value: "441", label: "آمونیوم نیترات" },
  { value: "442", label: "هیدروژن پراکسید" },
  { value: "443", label: "اسید سولفوریک" },
  { value: "444", label: "اسید هیدروفلوئوریک" },
  { value: "445", label: "اسید نیتریک" },
  { value: "446", label: "هیدروکسید سدیم" },
  { value: "447", label: "کلر مایع" },
  { value: "448", label: "آمونیاک مایع" },
  { value: "449", label: "سیلندرهای گاز تحت فشار" },
  { value: "450", label: "اکسیژن مایع" },
  { value: "451", label: "نیتروژن مایع" },
  { value: "452", label: "دی‌اکسید کربن مایع" },
  { value: "453", label: "هیدروژن مایع" },
  { value: "454", label: "اتیلن اکساید" },
  { value: "455", label: "فسفر سفید" },
  { value: "456", label: "کاربید کلسیم" },
  { value: "457", label: "لیتیوم فلزی" },
  { value: "458", label: "سدیم فلزی" },
  { value: "459", label: "پتاسیم فلزی" },
  { value: "460", label: "باتری‌های لیتیومی" },
  { value: "501", label: "توربین بخار" },
  { value: "502", label: "ژنراتور دیزلی" },
  { value: "503", label: "کمپرسورهای صنعتی" },
  { value: "504", label: "پمپ های سانتریفیوژ" },
  { value: "505", label: "مبدل حرارتی" },
  { value: "506", label: "دستگاه های CNC" },
  { value: "507", label: "راکتورهای شیمیایی" },
  { value: "508", label: "تسمه نقاله صنعتی" },
  { value: "509", label: "کوره های القایی" },
  { value: "510", label: "بویلرهای بخار صنعتی" },
  { value: "511", label: "چیلرهای صنعتی" },
  { value: "512", label: "برج‌های خنک‌کننده" },
  { value: "513", label: "فیلترهای صنعتی" },
  { value: "514", label: "روبات‌های صنعتی" },
  { value: "515", label: "سیستم‌های هیدرولیک" },
  { value: "516", label: "سیستم‌های پنوماتیک" },
  { value: "517", label: "الکتروموتورهای صنعتی" },
  { value: "518", label: "ترانسفورماتورهای قدرت" },
  { value: "519", label: "سیستم‌های UPS صنعتی" },
  { value: "520", label: "تابلوهای برق صنعتی" },
  { value: "521", label: "سیستم‌های اسکادا" },
  { value: "522", label: "PLC های صنعتی" },
  { value: "523", label: "سنسورهای صنعتی" },
  { value: "524", label: "سیستم‌های ارتینگ" },
  { value: "525", label: "میکسرهای صنعتی" },
  { value: "526", label: "خشک‌کن‌های صنعتی" },
  { value: "527", label: "پرس‌های هیدرولیک" },
  { value: "528", label: "دستگاه‌های جوش صنعتی" },
  { value: "529", label: "سیستم‌های تصفیه آب صنعتی" },
  { value: "530", label: "سیستم‌های تصفیه هوا" },
  { value: "531", label: "سیستم‌های آتش‌نشانی صنعتی" },
  { value: "532", label: "جرثقیل‌های سقفی" },
  { value: "533", label: "لیفتراک‌های صنعتی" },
  { value: "534", label: "ماشین‌آلات بسته‌بندی" },
  { value: "535", label: "ماشین‌آلات پرکن" },
  { value: "536", label: "سیستم‌های کنترل کیفیت خودکار" },
  { value: "537", label: "سیستم‌های توزین صنعتی" },
  { value: "538", label: "کابین‌های رنگ صنعتی" },
  { value: "539", label: "دستگاه‌های برش لیزری" },
  { value: "540", label: "دستگاه‌های واترجت صنعتی" },
  { value: "601", label: "الوار چوب طبیعی" },
  { value: "602", label: "تخته چندلایه (پلی‌وود)" },
  { value: "603", label: "تخته فیبر (MDF)" },
  { value: "604", label: "تخته نئوپان" },
  { value: "605", label: "روکش چوب طبیعی" },
  { value: "606", label: "لمینت چوبی" },
  { value: "607", label: "پارکت چوبی طبیعی" },
  { value: "608", label: "چهارتراش چوبی" },
  { value: "609", label: "تراورس چوبی" },
  { value: "610", label: "خاک اره فشرده" },
  { value: "611", label: "پالت چوبی" },
  { value: "612", label: "جعبه‌های چوبی صنعتی" },
  { value: "613", label: "قرقره‌های چوبی" },
  { value: "614", label: "تیرهای چوبی سازه‌ای" },
  { value: "615", label: "خمیر چوب" },
  { value: "616", label: "پنل‌های ضد آب" },
  { value: "617", label: "فیبر فشرده (HDF)" },
  { value: "618", label: "تخته‌های OSB" },
  { value: "619", label: "چیپس چوب" },
  { value: "620", label: "ذغال چوب صنعتی" },
  { value: "701", label: "پارچه پنبه‌ای خام" },
  { value: "702", label: "پارچه پلی‌استر" },
  { value: "703", label: "پارچه نایلون" },
  { value: "704", label: "پارچه ویسکوز" },
  { value: "705", label: "نخ پنبه‌ای" },
  { value: "706", label: "نخ پلی‌استر" },
  { value: "707", label: "نخ اکریلیک" },
  { value: "708", label: "الیاف پلی‌استر" },
  { value: "709", label: "الیاف پنبه" },
  { value: "710", label: "الیاف نایلون" },
  { value: "711", label: "پشم خام" },
  { value: "712", label: "ابریشم خام" },
  { value: "713", label: "پارچه دنیم" },
  { value: "714", label: "پارچه کتان" },
  { value: "715", label: "چرم طبیعی" },
  { value: "716", label: "چرم مصنوعی" },
  { value: "717", label: "پارچه کشباف" },
  { value: "718", label: "پارچه تافته" },
  { value: "719", label: "پارچه ساتن" },
  { value: "720", label: "پارچه مخمل" },
  { value: "721", label: "پارچه توری" },
  { value: "722", label: "پارچه ضدآب" },
  { value: "723", label: "پارچه ضدآتش" },
  { value: "724", label: "فوم لاتکس" },
  { value: "725", label: "اسفنج پلی‌اورتان" },
  { value: "726", label: "الیاف شیشه" },
  { value: "727", label: "الیاف کربن" },
  { value: "728", label: "ژئوتکستایل" },
  { value: "729", label: "منسوجات بی‌بافت" },
  { value: "730", label: "نمد صنعتی" },
  { value: "801", label: "بدنه خودرو" },
  { value: "802", label: "موتور خودرو" },
  { value: "803", label: "گیربکس اتوماتیک" },
  { value: "804", label: "گیربکس دستی" },
  { value: "805", label: "سیستم ترمز" },
  { value: "806", label: "سیستم تعلیق" },
  { value: "807", label: "سیستم فرمان" },
  { value: "808", label: "سیستم اگزوز" },
  { value: "809", label: "سیستم خنک‌کننده" },
  { value: "810", label: "رادیاتور خودرو" },
  { value: "811", label: "لاستیک خودرو" },
  { value: "812", label: "رینگ خودرو" },
  { value: "813", label: "باتری خودرو" },
  { value: "814", label: "سیستم برق خودرو" },
  { value: "815", label: "چراغ‌های خودرو" },
  { value: "816", label: "شیشه خودرو" },
  { value: "817", label: "آینه خودرو" },
  { value: "818", label: "سیستم تهویه خودرو" },
  { value: "819", label: "صندلی خودرو" },
  { value: "820", label: "داشبورد خودرو" },
  { value: "821", label: "سیستم سوخت‌رسانی" },
  { value: "822", label: "سیستم کنترل آلایندگی" },
  { value: "823", label: "سنسورهای خودرو" },
  { value: "824", label: "ECU خودرو" },
  { value: "825", label: "سیستم ایربگ" },
  { value: "901", label: "ضایعات آهن" },
  { value: "902", label: "ضایعات فولاد" },
  { value: "903", label: "ضایعات آلومینیوم" },
  { value: "904", label: "ضایعات مس" },
  { value: "905", label: "ضایعات برنج" },
  { value: "906", label: "ضایعات استیل" },
  { value: "907", label: "ضایعات سرب" },
  { value: "908", label: "ضایعات روی" },
  { value: "909", label: "ضایعات نیکل" },
  { value: "910", label: "ضایعات قلع" },
  { value: "911", label: "ضایعات تیتانیوم" },
  { value: "912", label: "ضایعات کروم" },
  { value: "913", label: "ضایعات چدن" },
  { value: "914", label: "ضایعات کابل مسی" },
  { value: "915", label: "براده‌های فلزی" },
  { value: "1001", label: "تجهیزات تصویربرداری پزشکی" },
  { value: "1002", label: "ابزار جراحی" },
  { value: "1003", label: "تجهیزات آزمایشگاهی" },
  { value: "1004", label: "مواد مصرفی پزشکی" },
  { value: "1005", label: "داروهای شیمیایی" },
  { value: "1006", label: "داروهای بیولوژیک" },
  { value: "1007", label: "ایمپلنت‌های پزشکی" },
  { value: "1008", label: "تجهیزات دندانپزشکی" },
  { value: "1009", label: "تجهیزات اورژانس" },
  { value: "1010", label: "تخت بیمارستانی" },
  { value: "1011", label: "پروتزهای پزشکی" },
  { value: "1012", label: "تجهیزات ارتوپدی" },
  { value: "1013", label: "تجهیزات استریلیزاسیون" },
  { value: "1014", label: "سیستم‌های تنفسی" },
  { value: "1015", label: "مواد آزمایشگاهی" },
  { value: "1016", label: "کیت‌های تشخیصی" },
  { value: "1017", label: "دستگاه‌های مانیتورینگ" },
  { value: "1018", label: "تجهیزات فیزیوتراپی" },
  { value: "1019", label: "محصولات یکبار مصرف پزشکی" },
  { value: "1020", label: "گازهای طبی" },
  { value: "1101", label: "قطعات میکروالکترونیک" },
  { value: "1102", label: "مدارهای چاپی (PCB)" },
  { value: "1103", label: "ریزپردازنده‌ها" },
  { value: "1104", label: "حافظه‌های نیمه‌هادی" },
  { value: "1105", label: "ترانزیستورها" },
  { value: "1106", label: "دیودها" },
  { value: "1107", label: "خازن‌ها" },
  { value: "1108", label: "مقاومت‌ها" },
  { value: "1109", label: "سلول‌های خورشیدی" },
  { value: "1110", label: "باتری‌های لیتیوم‌یونی" },
  { value: "1111", label: "باتری‌های نیکل-متال هیدرید" },
  { value: "1112", label: "سنسورهای الکترونیکی" },
  { value: "1113", label: "آنتن‌های مخابراتی" },
  { value: "1114", label: "مبدل‌های AC/DC" },
  { value: "1115", label: "اینورترهای DC/AC" },
  { value: "1116", label: "منابع تغذیه سوئیچینگ" },
  { value: "1117", label: "نمایشگرهای LCD" },
  { value: "1118", label: "نمایشگرهای LED" },
  { value: "1119", label: "نمایشگرهای OLED" },
  { value: "1120", label: "رله‌های الکترونیکی" },
  { value: "1121", label: "کلیدهای الکترونیکی" },
  { value: "1122", label: "فیبر نوری" },
  { value: "1123", label: "کابل‌های مسی" },
  { value: "1124", label: "کابل‌های کواکسیال" },
  { value: "1125", label: "مدارهای مجتمع (IC)" },
  { value: "1126", label: "بردهای توسعه الکترونیکی" },
  { value: "1127", label: "ماژول‌های WiFi" },
  { value: "1128", label: "ماژول‌های بلوتوث" },
  { value: "1129", label: "میکروکنترلرها" },
  { value: "1130", label: "FPGA و CPLD" },
  { value: "1201", label: "خوراک طیور" },
  { value: "1202", label: "خوراک دام سنگین" },
  { value: "1203", label: "کنسانتره دامی" },
  { value: "1204", label: "مکمل‌های خوراک دام" },
  { value: "1205", label: "پودر استخوان" },
  { value: "1206", label: "پودر ماهی" },
  { value: "1207", label: "پودر گوشت" },
  { value: "1208", label: "پوست خام دامی" },
  { value: "1209", label: "پشم خام گوسفند" },
  { value: "1210", label: "روغن ماهی صنعتی" },
  { value: "1211", label: "چربی حیوانی صنعتی" },
  { value: "1212", label: "شاخ و سم دامی" },
  { value: "1213", label: "کود دامی فرآوری شده" },
  { value: "1214", label: "واکسن‌های دامی" },
  { value: "1215", label: "داروهای دامپزشکی" },
  { value: "1301", label: "سدیم کربنات (سودا اش)" },
  { value: "1302", label: "سدیم بیکربنات" },
  { value: "1303", label: "کلسیم کربنات" },
  { value: "1304", label: "سیلیکات سدیم" },
  { value: "1305", label: "سولفات سدیم" },
  { value: "1306", label: "سولفات منیزیم" },
  { value: "1307", label: "اسید سیتریک خوراکی" },
  { value: "1308", label: "اسید استیک خوراکی" },
  { value: "1309", label: "گلیسیرین صنعتی" },
  { value: "1310", label: "سوربیتول" },
  { value: "1311", label: "نشاسته صنعتی" },
  { value: "1312", label: "پکتین" },
  { value: "1313", label: "کربوکسی متیل سلولز (CMC)" },
  { value: "1314", label: "هیدروکسی پروپیل متیل سلولز (HPMC)" },
  { value: "1315", label: "دی اکسید تیتانیوم" },
  { value: "1316", label: "کائولن" },
  { value: "1317", label: "بنتونیت" },
  { value: "1318", label: "تالک صنعتی" },
  { value: "1319", label: "سیلیکا ژل" },
  { value: "1320", label: "کربن فعال" },
  { value: "1321", label: "پلی آلومینیوم کلراید (PAC)" },
  { value: "1322", label: "اکسید روی" },
  { value: "1323", label: "اکسید منیزیم" },
  { value: "1324", label: "سوربات پتاسیم" },
  { value: "1325", label: "بنزوات سدیم" },
  { value: "1401", label: "تابلوهای نقاشی" },
  { value: "1402", label: "مجسمه‌های هنری" },
  { value: "1403", label: "فرش‌های دستباف" },
  { value: "1404", label: "آثار خوشنویسی" },
  { value: "1405", label: "مینیاتور و تذهیب" },
  { value: "1406", label: "صنایع دستی فلزی" },
  { value: "1407", label: "صنایع دستی چوبی" },
  { value: "1408", label: "صنایع دستی سفالی" },
  { value: "1409", label: "صنایع دستی سنگی" },
  { value: "1410", label: "زیورآلات هنری" },
  { value: "1501", label: "کاغذ تحریر" },
  { value: "1502", label: "کاغذ روزنامه" },
  { value: "1503", label: "کاغذ گلاسه" },
  { value: "1504", label: "کاغذ کرافت" },
  { value: "1505", label: "کاغذ کاربن‌لس" },
  { value: "1506", label: "مقوای بسته‌بندی" },
  { value: "1507", label: "کارتن آماده" },
  { value: "1508", label: "کاغذ بهداشتی صنعتی" },
  { value: "1509", label: "خمیر کاغذ" },
  { value: "1510", label: "کاغذ فیلتر صنعتی" },
  { value: "1511", label: "کاغذ حرارتی" },
  { value: "1512", label: "کاغذ ضد آب" },
  { value: "1513", label: "کاغذ عایق الکتریکی" },
  { value: "1514", label: "کاغذ دیواری صنعتی" },
  { value: "1515", label: "کاغذ لیبل و برچسب" },
  { value: "1601", label: "پلی‌اتیلن بازیافتی (PE)" },
  { value: "1602", label: "پلی‌پروپیلن بازیافتی (PP)" },
  { value: "1603", label: "پلی‌استایرن بازیافتی (PS)" },
  { value: "1604", label: "پلی‌وینیل کلراید بازیافتی (PVC)" },
  { value: "1605", label: "پلی‌اتیلن ترفتالات بازیافتی (PET)" },
  { value: "1606", label: "پلی‌کربنات بازیافتی (PC)" },
  { value: "1607", label: "ABS بازیافتی" },
  { value: "1608", label: "پلی‌امید بازیافتی (نایلون)" },
  { value: "1609", label: "پلی‌اورتان بازیافتی (PU)" },
  { value: "1610", label: "دانه‌های پلاستیک بازیافتی مخلوط" },
  { value: "1701", label: "کابل‌های قدرت" },
  { value: "1702", label: "کابل‌های کنترل" },
  { value: "1703", label: "ترانسفورماتورهای توزیع" },
  { value: "1704", label: "کلیدهای قدرت" },
  { value: "1705", label: "کلیدهای مینیاتوری" },
  { value: "1706", label: "کنتاکتورها" },
  { value: "1707", label: "رله‌های حفاظتی" },
  { value: "1708", label: "تابلوهای برق" },
  { value: "1709", label: "چراغ‌های صنعتی" },
  { value: "1710", label: "سیستم‌های روشنایی LED" },
  { value: "1711", label: "باتری‌های صنعتی" },
  { value: "1712", label: "یو پی اس‌های صنعتی" },
  { value: "1713", label: "ژنراتورهای برق" },
  { value: "1714", label: "الکتروموتورها" },
  { value: "1715", label: "درایوهای کنترل سرعت موتور" },
  { value: "1716", label: "سیستم‌های کنترل PLC" },
  { value: "1717", label: "سیستم‌های اعلام حریق" },
  { value: "1718", label: "سیستم‌های حفاظت صاعقه" },
  { value: "1719", label: "سیستم‌های ارتینگ" },
  { value: "1720", label: "تجهیزات اندازه‌گیری برق" },
  { value: "1801", label: "سیمان پرتلند" },
  { value: "1802", label: "سیمان پوزولانی" },
  { value: "1803", label: "گچ ساختمانی" },
  { value: "1804", label: "آهک ساختمانی" },
  { value: "1805", label: "شن و ماسه" },
  { value: "1806", label: "سنگدانه" },
  { value: "1807", label: "آجر فشاری" },
  { value: "1808", label: "آجر نسوز" },
  { value: "1809", label: "بلوک سیمانی" },
  { value: "1810", label: "بلوک سفالی" },
  { value: "1811", label: "تیرآهن" },
  { value: "1812", label: "میلگرد" },
  { value: "1813", label: "نبشی و ناودانی" },
  { value: "1814", label: "ورق گالوانیزه" },
  { value: "1815", label: "عایق رطوبتی" },
  { value: "1816", label: "عایق حرارتی" },
  { value: "1817", label: "عایق صوتی" },
  { value: "1818", label: "شیشه ساختمانی" },
  { value: "1819", label: "کاشی و سرامیک" },
  { value: "1820", label: "سنگ ساختمانی" },
  { value: "1821", label: "پانل گچی" },
  { value: "1822", label: "پروفیل آلومینیومی" },
  { value: "1823", label: "درب و پنجره UPVC" },
  { value: "1824", label: "لوله PVC ساختمانی" },
  { value: "1825", label: "لوله فولادی ساختمانی" },
  { value: "1826", label: "لوله پلی‌اتیلن" },
  { value: "1827", label: "اتصالات لوله" },
  { value: "1828", label: "چسب‌های ساختمانی" },
  { value: "1829", label: "رنگ و پوشش‌های ساختمانی" },
  { value: "1830", label: "بتن آماده" },
  { value: "1901", label: "کانتینر ۲۰ فوت" },
  { value: "1902", label: "کانتینر ۴۰ فوت" },
  { value: "1903", label: "مخازن فلزی" },
  { value: "1904", label: "مخازن فایبرگلاس" },
  { value: "1905", label: "تانکرهای حمل مایعات" },
  { value: "1906", label: "سیلوهای ذخیره" },
  { value: "1907", label: "سازه‌های فلزی پیش‌ساخته" },
  { value: "1908", label: "سوله‌های صنعتی" },
  { value: "1909", label: "داربست‌های ساختمانی" },
  { value: "1910", label: "قطعات بتنی پیش‌ساخته" },
  { value: "1911", label: "تیرهای برق بتنی" },
  { value: "1912", label: "لوله‌های بتنی قطور" },
  { value: "1913", label: "دکل‌های مخابراتی" },
  { value: "1914", label: "توربین‌های بادی" },
  { value: "1915", label: "پنل‌های خورشیدی صنعتی" }
];

const driverAccountSettingTextInput = [
  {
    title: "کد ملی",
    name: "nationalId",
    maxLength: 10,
    pattern: {
      type: /^\d{10}$/,
      message: "کد ملی 10 رقمی می‌باشد . "
    },
    keyboardType: Platform.OS === "ios" ? "name-phone-pad" : "number-pad"
  },
  {
    title: "نام کاربری",
    name: "userName",
    maxLength: 30,
    minLength: 4,
    keyboardType: "default"
  },
  {
    title: "شماره هوشمند راننده",
    name: "driverSmartNumber",
    maxLength: 8,
    pattern: {
      type: /^\d{8}$/,
      message: "هوشمند راننده 8 رقمی می‌باشد . "
    },
    keyboardType: Platform.OS === "ios" ? "name-phone-pad" : "number-pad"
  },
  {
    title: "شماره هوشمند خودرو",
    name: "truckSmartNumber",
    maxLength: 9,
    pattern: {
      type: /^\d{9}$/,
      message: "هوشمند خودرو 9 رقمی می‌باشد . "
    },
    keyboardType: Platform.OS === "ios" ? "name-phone-pad" : "number-pad"
  }
];

const cargoOwnerAccountSettingTextInput = [
  {
    title: "کد ملی",
    name: "nationalId",
    maxLength: 10,
    pattern: {
      type: /^\d{10}$/,
      message: "کد ملی 10 رقمی می‌باشد . "
    },
    keyboardType: Platform.OS === "ios" ? "name-phone-pad" : "number-pad"
  },
  {
    title: "نام کاربری",
    name: "userName",
    maxLength: 30,
    minLength: 4,
    keyboardType: "default"
  }
];

export {
  driverHomeBoxes,
  cargoOwnerHomeBoxes,
  tabBoxes,
  truckTypes,
  cargoTypes,
  driverAccountSettingTextInput,
  cargoOwnerAccountSettingTextInput
};
